# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Thevelop"

author:
  name:             "Tobias Scheepers"
  facebook:         your-id
  twitter:          your-id
  github:           "theveloped"
  linkedin:         your-id
  medium:           your-id
  tumblr:           your-id
  email:            thevelop@gmail.com
  google:           "101990278525964205044"

# URL
#url:                "https://AWEEKJ.github.io" # the base hostname & protocol for your site
url:                "https://theveloped.github.io" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Amsterdam
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           2
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/theveloped"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "archives"
    values:
      layout:       "archive"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
